CFLAGS = -std=gnu99
CC=gcc
LIB = -pthread


all: task1

task1: task1.c
	$(CC) $(CFLAGS) task1.c -o task1 $(LIB)



.PHONY: clean
clean:
	$(RM) task1 text0.txt text1.txt text2.txt text3.txt text4.txt text5.txt text6.txt text7.txt text8.txt text9.txt

